services:
  mysql:
    image: mysql:8.0
    container_name: simel-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker:/docker-entrypoint-initdb.d

  tomcat:
    build: .
    container_name: simel-tomcat
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: root
    restart: always
volumes:
  mysql_data: